### ISSUE TITLE
Prevent Deadlocks

### ISSUE THREAD

**Issue by bronumski** [mrb0nj/Slack.Webhooks#60]
```c#
        public virtual bool Post(SlackMessage slackMessage)
        {
            var result = PostAsync(slackMessage);
            return result.Result;
        }
```
Although one would wonder why the synchronous method above would be called from an async task, if where called it could result in a deadlock.
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
Consider rewriting it like this:
```c#
        public virtual bool Post(SlackMessage slackMessage)
        {
            var result = PostAsync(slackMessage);
            return result.GetAwaiter().GetResult();
        }
        // Or a one liner :)
        public virtual bool Post(SlackMessage slackMessage)
          => PostAsync(slackMessage).GetAwaiter().GetResult();
```
https://blog.stephencleary.com/2014/12/a-tour-of-task-part-6-results.html

**Comment by bronumski** [comment]
Having said that your probably okay just using the `.ConfigureAwait(false)` in the Post method.

**Comment by nerdfury** [comment]
Hi @bronumski thanks for the info, i like your original approach since it is clearer what is going on, will consider updating it soon :+1:
