### ISSUE TITLE
Custom emoji

### ISSUE THREAD

**Issue by winzig** [mrb0nj/Slack.Webhooks#61]
Would it make sense to have the capability to specify custom Emoji? This could be used both for custom emoji defined by individual Slack teams, as well as for missing emoji (e.g. I don't see 🤑 in the Emoji class currently).

Something along the lines of:

`var emoji = new Emoji(":money_mouth_face:");`

**Comment by pmacca** [comment]
I tend to agree the existing list appears hard to maintain and extend.
The ability to add any emoji name would be more flexible.

**Comment by mrb0nj** [comment]
I know this ticket has been open a loooooooong time but I would appreciate your thoughts on PR #67 if you get a chance.

also a pre-release version here https://github.com/mrb0nj/Slack.Webhooks/packages/42275

**Comment by winzig** [comment]
@mrb0nj I skimmed the PR, if the changes are what I think they are (moving to using ":string:" syntax to allow for custom emoji, with constants to cover most of the current emojis for easier reference), then it looks good to me, thanks!

**Comment by mrb0nj** [comment]
Yup that about sums it up, doing my best not to break anyone already using the constant Enum values in the process 👍
