### ISSUE TITLE
Missing emoji

### ISSUE THREAD

**Issue by wwarby** [mrb0nj/Slack.Webhooks#64]
card_file_box and card_index_dividers emojis seem to be missing from the library

**Comment by mrb0nj** [comment]
This has been open a while so apologies for that, proposed fix (overhaul) of Emoji's in PR #67 and a pre-release version here: https://github.com/mrb0nj/Slack.Webhooks/packages/42275

**Comment by mrb0nj** [comment]
v1.1.0 available on nuget which should fix this.
