### ISSUE TITLE
Unsigned Package

### ISSUE THREAD

**Issue by VoroninDA** [mrb0nj/Slack.Webhooks#70]
Greetings and Happy New Year!

It looks like when the package was uploaded to NuGet, it was not signed by the developer or by an organization. The public token = null.

Powershell:
([system.reflection.assembly]::loadfile("~\Slack.Webhooks.dll")).FullName
Output:
Slack.Webhooks, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null

**Comment by mxmissile** [comment]
Not signing is a good thing. You can sign it yourself btw, https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name
