### ISSUE TITLE
Cloning doesn't clone blocks

### ISSUE THREAD

**Issue by pleb** [mrb0nj/Slack.Webhooks#73]
While using `PostToChannelsAsync` and found it showed the `Message.Text` I set, but not the `Message.Blocks`. Further investigation lead me to the `Message.Clone` method where I discovered two things. 

First, it seems that copying/cloning of `Message.Blocks` was not added in the recent work to include blocks. 

And secondly, it's not a deep clone as referenced types (Attachments) are copied as-is, although this might not matter.

**Comment by mrb0nj** [comment]
Thanks @pleb will give the deep clone (potential) issue some thought!
